server {
    listen 80;

    # Корневая папка, куда мы скопировали билд React
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Главное правило для SPA:
    # 1. Попробуй найти файл ($uri)
    # 2. Попробуй найти папку ($uri/)
    # 3. Если не нашел — отдай index.html (React Router перехватит управление)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Проксирование API (Опционально, но полезно, чтобы избежать CORS)
    # Если фронт стучится на /api, пересылаем на бэкенд
    # location /api/ {
    #     proxy_pass http://api:8000;
    #     proxy_set_header Host $host;
    # }
}