[alembic]
script_location = src/migrations

# Добавляем текущую директорию в sys.path, чтобы Alembic видел src
prepend_sys_path = .

# Шаблон имени файла миграции: ГГГГ_ММ_ДД_ЧЧММ-хеш_название.py
# Это позволяет сортировать файлы в редакторе по хронологии (Time Complexity поиска глазами: O(1))
file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

sqlalchemy.url = postgresql+asyncpg://postgres:postgres@db:5432/car_ads_db

timezone = UTC

# --- Hooks (Автоформатирование) ---
# После создания файла миграции, Alembic автоматически запустит Ruff.
# Это гарантирует, что автосгенерированный код соответствует вашим стандартам.
[post_write_hooks]
#hooks = ruff

# Настройки для Ruff
ruff.type = exec
ruff.executable = ruff
ruff.options = format REVISION_SCRIPT_FILENAME

[post_write_hooks:ruff]
type = console_scripts
entrypoint = ruff
options = check --fix --unsafe-fixes REVISION_SCRIPT_FILENAME

# --- Logging Configuration ---
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S