"""add_mileage_and_image

Revision ID: 781d00edeb55
Revises: 8d23118857fe
Create Date: 2026-03-08 11:39:42.869714+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781d00edeb55'
down_revision: Union[str, None] = '8d23118857fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('ai_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'ai_description')
    # ### end Alembic commands ###