"""Add mileage and image_url

Revision ID: 6e9a710f88bd
Revises: e20cee93a186
Create Date: 2026-03-04 19:00:38.432799+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e9a710f88bd'
down_revision: Union[str, None] = 'e20cee93a186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('mileage', sa.Integer(), nullable=True))
    op.add_column('cars', sa.Column('image_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'image_url')
    op.drop_column('cars', 'mileage')
    # ### end Alembic commands ###